---
# init-examples/handlers/main.yml
- name: push landsat-parse
  command: sh -c 'docker tag -f landsat-parse:{{ example_image_tag }} {{ docker_registry }}landsat-parse:{{ example_image_tag }}; docker push {{ docker_registry }}landsat-parse:{{ example_image_tag }}'
  become: true

- name: push landsat-ndwi
  command: sh -c 'docker tag -f landsat-ndwi:{{ example_image_tag }} {{ docker_registry }}landsat-ndwi:{{ example_image_tag }}; docker push {{ docker_registry }}landsat-ndwi:{{ example_image_tag }}'
  become: true

- name: push landsat-tiles
  command: sh -c 'docker tag -f landsat-tiles:{{ example_image_tag }} {{ docker_registry }}landsat-tiles:{{ example_image_tag }}; docker push {{ docker_registry }}landsat-tiles:{{ example_image_tag }}'
  become: true

- name: push pca
  command: sh -c 'docker tag -f pca:{{ example_image_tag }} {{ docker_registry }}pca:{{ example_image_tag }}; docker push {{ docker_registry }}pca:{{ example_image_tag }}'
  become: true

- name: push vash
  command: sh -c 'docker tag -f vash:{{ example_image_tag }} {{ docker_registry }}vash:{{ example_image_tag }}; docker push {{ docker_registry }}vash:{{ example_image_tag }}'
  become: true

