---
- name: Kill static scale web server
  tags: scale-web-static
  docker:
    name: scale-web-static
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ docker_registry }}geoint/scale-web-static:{{ scale_docker_version }}'
    state: absent
  become: true

- name: Start static scale web server
  tags: [ scale-web-static, restart-scale ]
  docker:
    name: scale-web-static
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ docker_registry }}geoint/scale-web-static:{{ scale_docker_version }}'
    state: restarted
    pull: always
    restart_policy: always
    volumes_from: scale-scheduler
    links:
      - 'scale-scheduler:scale-web'
    ports:
      - '{{ host_http_port }}:80'
  become: true
