---
# scale-scheduler/tasks/main.yml
- name: Kill scheduler
  tags: scale-scheduler
  docker:
    name: scale-scheduler
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ docker_registry }}geoint/scale:{{ scale_docker_version }}'
    state: absent
  become: true

- name: Start scheduler
  tags: [ scale-scheduler, restart-scale ]
  docker:
    name: scale-scheduler
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ docker_registry }}geoint/scale:{{ scale_docker_version }}'
    state: restarted
    restart_policy: always
    pull: always
    command: 'scale_scheduler'
    net: default
    env:
      SCALE_SECRET_KEY: '$6$D6zJhmUX3htFBnBk$Mkl/xVyXS2In5eHrwXz2QzzspaHPQPMFrfoA7DPxifGx.5O4kzedqx1DO5PrdSF0VuO1XqMEmpAhrXecPC5y51'
      SCALE_DEBUG: 'False'
      SCALE_LOGGING_ADDRESS: 'udp://192.168.99.101:12201'
      SCALE_DB_USER: '{{ db_username }}'
      SCALE_DB_PASS: '{{ db_password }}'
      SCALE_DB_HOST: '{{ db_host }}'
      SCALE_API_URL: '{{ scale_api_url }}'
      MESOS_MASTER_URL: '{{ mesos_zk }}'
      SCALE_ZK_URL: '{{ scheduler_zk }}'
      SCALE_DOCKER_IMAGE: '{{ docker_registry }}geoint/scale'
      ENABLE_GUNICORN: '1'
  become: true
